class EndPoints:
    BASE_URL = "https://valorant-api.com/v1/"

    agents = BASE_URL + "agents"
    buddies = BASE_URL + "buddies"
    buddy_levels = buddies + "/levels"
    bundles = BASE_URL + "bundles"
    ceremonies = BASE_URL + "ceremonies"
    competitive_tiers = BASE_URL + "competitivetiers"
    content_tiers = BASE_URL + "contenttiers"
    contracts = BASE_URL + "contracts"
    currencies = BASE_URL + "currencies"
    events = BASE_URL + "events"
    gamemodes = BASE_URL + "gamemodes"
    gamemode_equip = gamemodes + "/equippables"
    gear = BASE_URL + "gear"
    maps = BASE_URL + "maps"
    player_cards = BASE_URL + "playercards"
    player_titles = BASE_URL + "playertitles"
    seasons = BASE_URL + "seasons"
    competitive_seasons = seasons + "/competitive"
    sprays = BASE_URL + "sprays"
    spray_levels = sprays + "/levels"
    themes = BASE_URL + "themes"
    weapons = BASE_URL + "weapons"
    weapons_skins = weapons + "/skins"
    weapons_skinchromas = weapons + "/skinchromas"
    weapons_skin_levels = weapons + "/skinlevels"

    version = BASE_URL + "version"
